
package proxyimpl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "InexistentAccountException", targetNamespace = "http://ProxyImpl/")
public class InexistentAccountException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InexistentAccountException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public InexistentAccountException_Exception(String message, InexistentAccountException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public InexistentAccountException_Exception(String message, InexistentAccountException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: proxyimpl.InexistentAccountException
     */
    public InexistentAccountException getFaultInfo() {
        return faultInfo;
    }

}
