
package proxyimpl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AccountManagerProxyImplService", targetNamespace = "http://ProxyImpl/", wsdlLocation = "http://localhost:12349/AccountManagerProxy1?wsdl")
public class AccountManagerProxyImplService
    extends Service
{

    private final static URL ACCOUNTMANAGERPROXYIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(proxyimpl.AccountManagerProxyImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = proxyimpl.AccountManagerProxyImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:12349/AccountManagerProxy1?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:12349/AccountManagerProxy1?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ACCOUNTMANAGERPROXYIMPLSERVICE_WSDL_LOCATION = url;
    }

    public AccountManagerProxyImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountManagerProxyImplService() {
        super(ACCOUNTMANAGERPROXYIMPLSERVICE_WSDL_LOCATION, new QName("http://ProxyImpl/", "AccountManagerProxyImplService"));
    }

    /**
     * 
     * @return
     *     returns AccountManagerProxyImpl
     */
    @WebEndpoint(name = "AccountManagerProxyImplPort")
    public AccountManagerProxyImpl getAccountManagerProxyImplPort() {
        return super.getPort(new QName("http://ProxyImpl/", "AccountManagerProxyImplPort"), AccountManagerProxyImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountManagerProxyImpl
     */
    @WebEndpoint(name = "AccountManagerProxyImplPort")
    public AccountManagerProxyImpl getAccountManagerProxyImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ProxyImpl/", "AccountManagerProxyImplPort"), AccountManagerProxyImpl.class, features);
    }

}
