
package partitionimpl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AccountManagerPartitionService", targetNamespace = "http://PartitionImpl/", wsdlLocation = "http://localhost:12348/AccountManagerPartition1?wsdl")
public class AccountManagerPartitionService
    extends Service
{

    private final static URL ACCOUNTMANAGERPARTITIONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(partitionimpl.AccountManagerPartitionService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = partitionimpl.AccountManagerPartitionService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:12348/AccountManagerPartition1?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:12348/AccountManagerPartition1?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ACCOUNTMANAGERPARTITIONSERVICE_WSDL_LOCATION = url;
    }

    public AccountManagerPartitionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountManagerPartitionService() {
        super(ACCOUNTMANAGERPARTITIONSERVICE_WSDL_LOCATION, new QName("http://PartitionImpl/", "AccountManagerPartitionService"));
    }

    /**
     * 
     * @return
     *     returns AccountManagerPartition
     */
    @WebEndpoint(name = "AccountManagerPartitionPort")
    public AccountManagerPartition getAccountManagerPartitionPort() {
        return super.getPort(new QName("http://PartitionImpl/", "AccountManagerPartitionPort"), AccountManagerPartition.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountManagerPartition
     */
    @WebEndpoint(name = "AccountManagerPartitionPort")
    public AccountManagerPartition getAccountManagerPartitionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://PartitionImpl/", "AccountManagerPartitionPort"), AccountManagerPartition.class, features);
    }

}
