
package partitionimpl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AccountManagerPartition", targetNamespace = "http://PartitionImpl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccountManagerPartition {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws InexistentAccountException_Exception
     * @throws NegativeAmountException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "transfer", targetNamespace = "http://PartitionImpl/", className = "partitionimpl.Transfer")
    @ResponseWrapper(localName = "transferResponse", targetNamespace = "http://PartitionImpl/", className = "partitionimpl.TransferResponse")
    public void transfer(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        double arg3)
        throws InexistentAccountException_Exception, NegativeAmountException_Exception
    ;

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "printBranchAndAccounts", targetNamespace = "http://PartitionImpl/", className = "partitionimpl.PrintBranchAndAccounts")
    @ResponseWrapper(localName = "printBranchAndAccountsResponse", targetNamespace = "http://PartitionImpl/", className = "partitionimpl.PrintBranchAndAccountsResponse")
    public void printBranchAndAccounts();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws InexistentAccountException_Exception
     * @throws NegativeAmountException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "credit", targetNamespace = "http://PartitionImpl/", className = "partitionimpl.Credit")
    @ResponseWrapper(localName = "creditResponse", targetNamespace = "http://PartitionImpl/", className = "partitionimpl.CreditResponse")
    public void credit(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2)
        throws InexistentAccountException_Exception, NegativeAmountException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(operationName = "GetBranchIterator")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetBranchIterator", targetNamespace = "http://PartitionImpl/", className = "partitionimpl.GetBranchIterator")
    @ResponseWrapper(localName = "GetBranchIteratorResponse", targetNamespace = "http://PartitionImpl/", className = "partitionimpl.GetBranchIteratorResponse")
    public int getBranchIterator(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws InexistentAccountException_Exception
     * @throws NegativeAmountException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "debit", targetNamespace = "http://PartitionImpl/", className = "partitionimpl.Debit")
    @ResponseWrapper(localName = "debitResponse", targetNamespace = "http://PartitionImpl/", className = "partitionimpl.DebitResponse")
    public void debit(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2)
        throws InexistentAccountException_Exception, NegativeAmountException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculateExposure", targetNamespace = "http://PartitionImpl/", className = "partitionimpl.CalculateExposure")
    @ResponseWrapper(localName = "calculateExposureResponse", targetNamespace = "http://PartitionImpl/", className = "partitionimpl.CalculateExposureResponse")
    public double calculateExposure(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
