SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `GameServer` DEFAULT CHARACTER SET latin1 ;
USE `GameServer` ;

-- -----------------------------------------------------
-- Table `GameServer`.`statistics`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `GameServer`.`statistics` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `ip` VARCHAR(45) NULL DEFAULT NULL ,
  `wins` INT NULL DEFAULT NULL ,
  `ties` INT NULL DEFAULT NULL ,
  `loses` INT NULL DEFAULT NULL ,
  `coins` INT NULL DEFAULT NULL ,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
